#!/bin/bash
echo "------------------------------------------"
echo "  🌿 BOTAN LINUX"
echo "------------------------------------------"
echo "  Base: Arch Linux Baseline"
echo "  Shell: Bash"
echo "  Bootloader: Limine"
echo "  Status: Hardcore Mode"
echo "------------------------------------------"
